---
version: "3"
services:
 devopsdb:
   image: renuboddu/automate:db
   ports:
     - "3306:3306"

 application:
   image: renuboddu/automate:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
